### ISSUE TITLE
Overflow from page 2!

### ISSUE THREAD

**Issue by Sandile-Dev01** [devdewa/adityawarman-dewa-putra#1]
The portfolio is good overall but there is overflow from page 2 to the last page when I view it on my desktop

**Comment by devdewa** [comment]
do you mean delay / lag when moving from page 2 to 4?

**Comment by devdewa** [comment]
do you mean delay / lag when moving from page 2 to 4?

**Comment by Sandile-Dev01** [comment]
Nope, the whole page is giving a overflow scroll, which means some elements in the page are beyond the view port, which makes the website looks unresponsive at desktop screens.

**Comment by devdewa** [comment]
Sorry, actually the concept is like that, only page 1 doesn't have overflow Y / full h-screen. Because pages 2 to 4 will continue to add content and require overflow. 

Therefore, I give the fixed styling for navigation on page 2-4 to stay in top layout when scrolling.

**Comment by devdewa** [comment]
maybe as a marker later I will add the "down arrow" icon and when scrolled it will disappear/hidden.

**Comment by devdewa** [comment]
btw thanks for reviewing my repo 🙏
